### ISSUE TITLE
Similar project

### ISSUE THREAD

**Issue by theoryshaw** [nsreed/ouronote#14]
Hi @nsreed, 
Seem like a cool project evolving here. 
You might want to check out https://gitlab.com/MeldCE/first-draft --a similar project built with paper.js and node.
Might help inform development.

**Comment by nsreed** [comment]
Thanks, I'll definitely check this out! It's good to know I'm not the only one exploring this approximate stack :).

I should probably make the predecessor to this project public. While it's an absolute mess, it's got about 5 years worth of prior feature development compared to ouronote. A good deal of that code is more or less vanilla paper.js code for tools, UI elements, & paper.js performance tweaks. The goal of this project is to get a peer to peer graph database, Gun.js, working as seamlessly and as transparently as possible under paper.js, at which point I can just drop all of my previous paper code in here.

**Comment by ultimape** [comment]
I'm going to close this for now to avoid clogging our issue repository.

But It does raise the neat idea of sharing other projects somewhere for users looking for alternatives. For example, I'd love to recommend Krita, Inkscape, Glimpse/Gimp to people somewhere to support the existing FOSS art community. I'd love to promote projects like MeldCE that might be useful for other uses case.
