### ISSUE TITLE
Backup Image Data to a file, Import/Export?

### ISSUE THREAD

**Issue by ultimape** [nsreed/ouronote#21]
While testing, we ran into a bug and then proceeded to delete accounts locally and in the process lost access to a drawing.

Occurred to me it would be useful to have a save/download/export and load/upload/import feature to allow for backups in case of replication failure and peer loss.

Long term this may be covered by gun implementing IPFS connectivity, but for the time being just having something that can be deposited into a .json would be enough.

I suspect it wouldn't be much different from the bug report feature in how it's implemented in the UI.

**Comment by nsreed** [comment]
You're correct. This isn't too far removed from the current bug report JSON, specifically the "graph" key. This key in theory contains all the data necessary to repopulate the graph database for any user and images which have been loaded by your browser. Individual images likewise. Part of the challenge in the long run is that your images may contain external references which haven't been seen by your browser, meaning, there is no guarantee that what you download will be a "full" copy of your data, though it would represent what you see in the editor.

If I understand correctly, the gun/ipfs bridge was implemented, but its use is discouraged. I need to refresh my understanding of this though.

**Comment by nsreed** [comment]
This feature is tentatively implemented in #33, now merged to master. It only handles paper.js format JSON imports, but as a MVP, is this acceptable?

**Comment by nsreed** [comment]
Closing the issue. Enhancement requests can be new issues.
