### ISSUE TITLE
user-friendly board sharing

### ISSUE THREAD

**Issue by nsreed** [nsreed/ouronote#7]
Currently, sharing a board requires setting up a certificate and sending a link to the board to the desired user outside of ouronote. This should be a more concise process.

**Comment by nsreed** [comment]
Extremely primitive messaging is now implemented, allowing sending the URL of vectors from user to user. To receive messages, users must first visit their profile settings allow incoming messages. This should eventually be introduced into account creation.

**Comment by ultimape** [comment]
Registering a board that was visited would make it easier to navigate to it again. The current process of pasting the URL to a new tab, logging in, and then pasting it again is tiresome when you gotta do this ever time you wanna access a board you didn't create. Particularly when done via a mobile browser with clumsy copy/paste options.

**Comment by nsreed** [comment]
Ideally, boards will have a star/add to favorites icon button in the editor, which you can use to add them to your list. It's looking more and more like I'll need to add a gun service worker, which among other things, would address the issue of needing to log in to every tab.

**Comment by nsreed** [comment]
This is implemented in #33
